### ISSUE TITLE
The next sentence after the comma in the tooltip disappears

### ISSUE THREAD

**Issue by AlexanderFishcake** [de-jcup/eclipse-sql-editor#24]
![image](https://user-images.githubusercontent.com/76913650/147995183-3b2734cf-4f1e-42f5-97cd-8adb803fc6f8.png)

When you first save the tooltip, offline description is normally displayed.
However, when IDE is restarted, if a 'comma' is included in the custom keyword tooltip, the next statement of the comma is deleted.
It was not deleted when tested with several different punctuation marks.
Add: Modifying and saving the saved tooltips seems normal, but restarting the IDE seems to change the modified tooltips to the previous value. In other words, once the tooltip is saved, it seems that it cannot be modified.
It is not known whether this is a phenomenon that only happens to me.

**Comment by de-jcup** [comment]
Hello @AlexanderFishcake , this odd situation also happens at my machine

PS: as a workaround in the meantime: just delete the custom keyword in preferences and create a new one with new tooltip. Cumbersme but this works...

## Steps to reproduce:
1. change a existing custom keyword tooltip
2. apply and close
3. check tooltip is shown inside editor changed now...
4. restart eclipse
5. check tooltip --> old tooltip appears but not changed one.
