### ISSUE TITLE
Make syntax highlighting styles customizable

### ISSUE THREAD

**Issue by vladchuk** [de-jcup/eclipse-sql-editor#26]
Please add an option to enable using bold typeface for custom keywords.

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/162134206-28216941-28e0-406a-b55d-1af91920bc70.png)

Is based internally on eclipse commons dialog.

So either a special `boolean` preference entry for custom keywords 
or a change inside eclipse-commons necessary.

**Comment by de-jcup** [comment]
With last commit it is possible to define "bold", "italic", "bold + italic" or "none" style for syntax elements:

![image](https://user-images.githubusercontent.com/11644753/171120454-2ed685e6-ed18-478b-84b3-f6cce2412c8d.png)

For custom keywords the default is now "bold" like for other statements.

**Comment by vladchuk** [comment]
Excellent. Thank you!
