### ISSUE TITLE
Add missing keywords DECLARE, INTO//syntax highlighting improvements

### ISSUE THREAD

**Issue by imkreislaufen** [de-jcup/eclipse-sql-editor#8]
Not all SQL keywords are being highlighted, e.g.
`DECLARE` --not highlighted
`INSERT INTO myTable` --`INTO` not highlighted

Keywords in general are not highlighted if symbols like `;` or `)` follow directly e.g.
`DECLARE myInt INTEGER;` --`INTEGER` not highlighted
`INSERT INTO tableName(column1, column2 ...) VALUES(value1, value2, ...);` --`VALUES` not highlighted

![image](https://user-images.githubusercontent.com/25757919/78363114-85a8fc80-75bb-11ea-8c25-a6a3762649b5.png)

P.S. huge fan of your editor

**Comment by de-jcup** [comment]
Will be fixed with Version 1.1.0 :
![image](https://user-images.githubusercontent.com/11644753/78463126-a10a2980-76d9-11ea-840e-707e5e1c7911.png)

**Comment by de-jcup** [comment]
Improved syntax highlighting

- fixes wanted initially by this issue
- functions have now dedicated tooltips
- added standard SQL functions
- functions no longer bold rendered
- default color for function statements is now middle yellow in dark mode
- added dark.css - initial colouring for dark theme should now work out of the box

Improved tooltips and syntax highlight word end checks
- "(" "," and ";" are now recognized as tooltip termination beside whitespaces
- so correct highlighted and also recognized for tooltip / hover handling

**Comment by de-jcup** [comment]
@imkreislaufen Just released version 1.1.0 on eclipse marketplace

**Comment by imkreislaufen** [comment]
I never imagined you would react and implement my suggestions this quickly. I'm more than impressed
